name: 🔍 Continuous Integration

on:
  push:
    branches: [ main, staging, develop ]
  pull_request:
    branches: [ main, staging ]

jobs:
  quality-checks:
    name: 🧪 Quality Checks
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4
        
      - name: 🔧 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: 📥 Install dependencies
        run: npm ci
        
      - name: 🎨 Check code formatting
        run: npm run format:check
        
      - name: 🔍 Lint code
        run: npm run lint
        
      - name: 📝 Type check
        run: npm run type-check
        
      - name: 🏗️ Build applications
        run: npm run build
        
      - name: 🧪 Run tests (if available)
        run: npm test --if-present

  security-audit:
    name: 🔒 Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4
        
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: 📥 Install dependencies
        run: npm ci
        
      - name: 🔒 Run security audit
        run: npm audit --audit-level=moderate
        
      - name: 📊 Check for outdated packages
        run: npm outdated || true

  dependency-review:
    name: 🔍 Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.repository_visibility == 'public'
    
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4
        
      - name: 🔍 Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          
  manual-dependency-check:
    name: 🔍 Manual Dependency Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.repository_visibility == 'private'
    
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4
        
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: 📥 Install dependencies
        run: npm ci
        
      - name: 🔍 Check for known vulnerabilities
        run: npm audit --audit-level=moderate
        
      - name: 📊 List dependency changes (if any)
        run: |
          echo "📋 Checking for package.json changes..."
          git diff origin/main..HEAD --name-only | grep -E "(package\.json|package-lock\.json)" || echo "No dependency changes detected"
          
      - name: 🚨 Security advisory check
        run: |
          echo "🔒 Running enhanced security check..."
          npm audit --audit-level=low --json > audit-results.json || true
          
          # Check if there are any vulnerabilities
          if [ -s audit-results.json ]; then
            echo "⚠️ Security audit results found. Please review:"
            cat audit-results.json | jq -r '.vulnerabilities // empty | to_entries[] | "- \(.key): \(.value.severity)"' || echo "Raw audit output available"
          else
            echo "✅ No security vulnerabilities detected"
          fi
